export const USER_STATUS = {
  LOGIN: 'LOGIN',
  WAITING: 'WAITING',
  ENTERING: 'ENTERING',
  SELECTING_SEAT: 'SELECTING_SEAT',
  ADMIN: 'ADMIN',
};

export const USER_LEVEL = {
  LOGIN: 0,
  WAITING: 1,
  ENTERING: 2,
  SELECTING_SEAT: 3,
  ADMIN: 4,
};
