export const getSeatResponseExample = {
  id: 1,
  layout: {
    overview: 'https://example.com/overview.svg',
    sections: [
      {
        id: 2,
        name: 'Section A',
        colLen: 5,
        seats: [
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
        ],
      },
      {
        id: 3,
        name: 'Section B',
        colLen: 5,
        seats: [
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
        ],
      },
      {
        id: 4,
        name: 'Section C',
        colLen: 5,
        seats: [
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
          'T',
          'F',
          'T',
          'T',
          'F',
        ],
      },
    ],
  },
};
